apiVersion: apps/v1
kind: Deployment
metadata:
  name: self-healing-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: self-healing-demo
  template:
    metadata:
      labels:
        app: self-healing-demo
    spec:
      containers:
        - name: app
          image: nginx:1.27
          command: ["/bin/sh", "-c"]
          args: ["exit 1"]  
          ports:
            - containerPort: 80
